/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.*;

/**
 *
 * @author Dylan Montiel Zúñiga
 * @version 1.0
 */
public class GUI_MENU_PRINCIPAL extends javax.swing.JFrame {

  /**
   * Creates new form GUI_MENU_PRINCIPAL
   */
  private Controlador_GUI_MENU_PRINCIPAL controlador_GUI_MENU_PRINCIPAL;
  
  public GUI_MENU_PRINCIPAL() {
    initComponents();
    setLocationRelativeTo(null);
    controlador_GUI_MENU_PRINCIPAL = new Controlador_GUI_MENU_PRINCIPAL(this);
    Jbtn_Salir.addActionListener(controlador_GUI_MENU_PRINCIPAL);
    Jbtn_AbrirTXT.addActionListener(controlador_GUI_MENU_PRINCIPAL);
    Jbtn_AplicarAlgoritmo.addActionListener(controlador_GUI_MENU_PRINCIPAL);
  }

  public void abrirTXT() {
    JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto", "txt");
    fileChooser.setFileFilter(filter);

    int resultado = fileChooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
      File archivoSeleccionado = fileChooser.getSelectedFile();
      String contenido = ManejoArchivos.leerArchivo(archivoSeleccionado.getAbsolutePath());
      Jta_Entrada.setText(contenido);
    }
  }
  
  public void aplicarAlgoritmo() {
    if (Jta_Entrada.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Debes abrir un archivo para aplicar algún algorítmo", "Error", JOptionPane.ERROR_MESSAGE);                
    }
    String operacion = Jcb_Operacion.getSelectedItem().toString().trim();
    String algoritmo = Jcb_Algoritmo.getSelectedItem().toString().trim();
    String contenido = Jta_Entrada.getText();
    
    switch (algoritmo) {
      case "Cifrado César":
        CifradoCesar cifradoCesar = new CifradoCesar();
        if (operacion == "Cifrado") {
          contenido = cifradoCesar.cifrar(contenido);
        } else {
          contenido = cifradoCesar.descifrar(contenido);
        }
        Jta_Salida.setText(contenido);
        break;
    }
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Jp_Opciones = new javax.swing.JPanel();
    Jl_OperacionRealizar = new javax.swing.JLabel();
    Jcb_Operacion = new javax.swing.JComboBox<>();
    Jl_Algoritmo = new javax.swing.JLabel();
    Jcb_Algoritmo = new javax.swing.JComboBox<>();
    Jl_Entrada = new javax.swing.JLabel();
    Jta_Entrada = new java.awt.TextArea();
    Jbtn_AbrirTXT = new javax.swing.JButton();
    Jbtn_AplicarAlgoritmo = new javax.swing.JButton();
    Jl_Salida = new javax.swing.JLabel();
    Jbtn_Salir = new javax.swing.JButton();
    Jbtn_EnviarCorreo = new javax.swing.JButton();
    Jta_Salida = new java.awt.TextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    Jp_Opciones.setBackground(new java.awt.Color(255, 255, 255));

    Jl_OperacionRealizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Jl_OperacionRealizar.setText("Operación a realizar:");

    Jcb_Operacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cifrado", "Descifrado" }));

    Jl_Algoritmo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Jl_Algoritmo.setText("Algoritmo:");

    Jcb_Algoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cifrado César", "Cifrado por Llave", "Sustitución Vigenére" }));

    Jl_Entrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Jl_Entrada.setText("Entrada");

    Jta_Entrada.setEditable(false);
    Jta_Entrada.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    Jbtn_AbrirTXT.setText("Abrir archivo TXT");

    Jbtn_AplicarAlgoritmo.setText("Aplicar algorítmo");
    Jbtn_AplicarAlgoritmo.setActionCommand("Aplicar algoritmo");

    Jl_Salida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Jl_Salida.setText("Salida");

    Jbtn_Salir.setText("Salir");

    Jbtn_EnviarCorreo.setText("Enviar por correo");

    Jta_Salida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    Jta_Salida.setEditable(false);

    javax.swing.GroupLayout Jp_OpcionesLayout = new javax.swing.GroupLayout(Jp_Opciones);
    Jp_Opciones.setLayout(Jp_OpcionesLayout);
    Jp_OpcionesLayout.setHorizontalGroup(
      Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(Jp_OpcionesLayout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(Jl_OperacionRealizar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(Jcb_Operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, Short.MAX_VALUE)
        .addComponent(Jl_Algoritmo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(Jcb_Algoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(198, 198, 198))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_OpcionesLayout.createSequentialGroup()
        .addContainerGap(30, Short.MAX_VALUE)
        .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_OpcionesLayout.createSequentialGroup()
            .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(Jp_OpcionesLayout.createSequentialGroup()
                .addComponent(Jl_Entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jbtn_AbrirTXT))
              .addComponent(Jta_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30))
          .addGroup(Jp_OpcionesLayout.createSequentialGroup()
            .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(Jbtn_EnviarCorreo)
              .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(Jl_Salida, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Jta_Salida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
      .addGroup(Jp_OpcionesLayout.createSequentialGroup()
        .addGap(318, 318, 318)
        .addComponent(Jbtn_AplicarAlgoritmo)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_OpcionesLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(Jbtn_Salir)
        .addGap(340, 340, 340))
    );
    Jp_OpcionesLayout.setVerticalGroup(
      Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(Jp_OpcionesLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Jl_OperacionRealizar)
          .addComponent(Jcb_Operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Jl_Algoritmo)
          .addComponent(Jcb_Algoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(25, 25, 25)
        .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(Jl_Entrada)
          .addComponent(Jbtn_AbrirTXT))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(Jta_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22)
        .addComponent(Jbtn_AplicarAlgoritmo)
        .addGap(18, 18, 18)
        .addComponent(Jl_Salida)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(Jta_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(19, 19, 19)
        .addComponent(Jbtn_EnviarCorreo)
        .addGap(18, 18, 18)
        .addComponent(Jbtn_Salir)
        .addContainerGap(26, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Jp_Opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(Jp_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI_MENU_PRINCIPAL().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Jbtn_AbrirTXT;
  private javax.swing.JButton Jbtn_AplicarAlgoritmo;
  private javax.swing.JButton Jbtn_EnviarCorreo;
  private javax.swing.JButton Jbtn_Salir;
  private javax.swing.JComboBox<String> Jcb_Algoritmo;
  private javax.swing.JComboBox<String> Jcb_Operacion;
  private javax.swing.JLabel Jl_Algoritmo;
  private javax.swing.JLabel Jl_Entrada;
  private javax.swing.JLabel Jl_OperacionRealizar;
  private javax.swing.JLabel Jl_Salida;
  private javax.swing.JPanel Jp_Opciones;
  private java.awt.TextArea Jta_Entrada;
  private java.awt.TextArea Jta_Salida;
  // End of variables declaration//GEN-END:variables
}
